version: '3.7'

services:
  mqttbroker:
    image: vernemq/vernemq:1.11.0-alpine
    ports:
      - 8888:8080
    environment:
      - "DOCKER_VERNEMQ_ACCEPT_EULA=yes"
      - "DOCKER_VERNEMQ_LOG__CONSOLE=both"
      - "DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=debug"
      - "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on"
      - "DOCKER_VERNEMQ_LISTENER__WS__ALLOWED_PROTOCOL_VERSIONS=3,4"
      - "DOCKER_VERNEMQ_LISTENER__WS__PROXY_PROTOCOL_USE_CN_AS_USERNAME=on"
      - "DOCKER_VERNEMQ_LISTENER__WS__PROXY_PROTOCOL=on"
      - "DOCKER_VERNEMQ_LISTENER__WS__DEFAULT=0.0.0.0:8080"
      - "DOCKER_VERNEMQ_VMQ_ACL__ACL_FILE=/etc/vernemq_custom/vmq.acl"
      - "DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES=30000"
      - "DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES=30000"
      - "DOCKER_VERNEMQ_LISTENER__MAX_CONNECTIONS=25000"
    volumes:
      - ./etc/vernemq:/etc/vernemq_custom:ro
      - ./etc/vernemq/vernemq_data:/vernemq/data